### ISSUE TITLE
Support BGS creations

### ISSUE THREAD

**Issue by pStyl3** [loot/starfield#53]
In order to support these official BGS creations, we need to know their plugin names.

- [x] [Allied Winter Camo Skin Pack](https://creations.bethesda.net/en/starfield/details/4d2573b0-b5fb-4e18-ad2a-eb93243e9338/Allied_Winter_Camo_Skin_Pack/) (300 CC)
- [x] [CombaTech Digital Camo Skin Pack](https://creations.bethesda.net/en/starfield/details/6cb482a0-9fb6-48f5-ad69-c4c40d830bd5/CombaTech_Digital_Camo_Skin_Pack/) (300 CC)
- [x] [Creature Plushie Set](https://creations.bethesda.net/en/starfield/details/a4c2c041-fcd5-455b-a8a4-41e106ba3de1/Creature_Plushie_Set/) (300 CC)
- [x] [Escape](https://creations.bethesda.net/en/starfield/details/1106af41-fac5-431e-aa1a-163b3e5d2892/Escape/) (500 CC)

**Comment by pStyl3** [comment]
I've added the official BGS creations `Allied Winter Camo Skin Pack`, `Creature Plushie Set` and `Escape` to the list, that were added on the 20th of August 2024.

// Edit
Escape (`sfbgs00b.esm`) added by **DJLegends1011** in https://github.com/loot/starfield/pull/57

**Comment by Aimdru** [comment]
Allied Winter Camo Skin Pack  -  sfbgs02b_a.esm
CombaTech Digital Camo Skin Pack  -  sfbgs00f_a.esm
Creature Plushie Set  -  sfbgs031.esm

**Comment by Aimdru** [comment]
StarSim: Mining Conglomerate  -  qog-miningconglomerate.esm
Starfield Core  -  qog-starfieldcore.esm
Beowulf Healthy Parts  -  beowulfhealthyparts.esm
Additional Weapon Icons  -  additionalweaponicons.esm
Baka REV-8 Hauler    -    bakarev8hauler.esm
Shade's Vehicle Tuner  -  shades_vehicle_tuner.esm
Starfield Extended - Aggressive Leveled NPCs      -     starfield extended - aggressive leveled npcs.esm
D.E.R.E.K.  -   sksfderek.esm
Life of Crime - Crimson Market     -     loc-crimsonmarket.esm

**Comment by Aimdru** [comment]
Neon Ramen  -  ramen.esm
Quantum Stealth Operations (QSO) Safehouse -  qso safehouse.esm
Interesting Points of Interest  - mk_pois.esm
EliTek Aerospace - Crimson Fleet ship habs  -  ceejcrimsonhabs.esm
Hide Empty Ship Habs  -  onek_noemptyshiphabs.esm
Allied HVAP Assault Carbine (Not Rifle)  -  weap_hvap.esm

**Comment by pStyl3** [comment]
Thanks for the plugin names of the official BGS creations, I'm gonna add them in a bit.

The rest of the plugin names we wouldn't add to the masterlist just for the sake of it. If there is a specific reason to add them, then yes of course we can add them (we would need to know the reason, e.g. if they should load in a specific spot or if we should attach a message to them). Then we would also require links to where those plugins can be downloaded from.

**Comment by Aimdru** [comment]
Enforcer - Tactical Pistol  -  novafinch_enforcerpistol.esm


> Thanks for the plugin names of the official BGS creations, I'm gonna add them in a bit.
> 
> The rest of the plugin names we wouldn't add to the masterlist just for the sake of it. If there is a specific reason to add them, then yes of course we can add them (we would need to know the reason, e.g. if they should load in a specific spot or if we should attach a message to them). Then we would also require links to where those plugins can be downloaded from.

links can be easily found in the creativity club by my titles. If you don't need it, then I'm gone. I still have plenty of this... There are also partial or full translations of RU

**Comment by pStyl3** [comment]
I've added the offcial BGS creations, thanks!

The rest of the list, while interesting, doesn't really help much. *Why* do you want to have these added to the masterlist? If there are valid reasons and we know these reasons, then it's no problem adding them. However, in contrast to the ones the initial post of this issue is talking about, those other plugins are not made by Bethesda - which means that there needs to be a purpose in adding them to the masterlist. Just the fact that they are part of the Verified Creations program is not a good enough reason to add them, as verified creations (apart from the ones made by Bethesda themselves) are not considered "official content".

As such I'm closing this issue. If you feel that some of the other mentioned plugins still should be added to the masterlist, please open a new issue for each case, with information on why it should be added & a link to where the mod can be downloaded from.
