### ISSUE TITLE
Support BGS Creation: Civilian Survival Suit

### ISSUE THREAD

**Issue by pStyl3** [loot/starfield#64]
In order to support this official BGS creation, we need to know it's plugin name.

- [x] [Civilian Survival Suit](https://creations.bethesda.net/en/starfield/details/66311a58-23a4-4950-9b25-d70f693fadc0/Civilian_Survival_Suit/) (500 CC)

**Comment by MacSplody** [comment]
According to [Starfield Wiki](https://starfieldwiki.net/wiki/Starfield:Civilian_Survival_Suit), the filename is `sfbgs024.esm`.

**Comment by pStyl3** [comment]
Thanks, seems like that wiki now features the filenames for the other creations as well.
